config/routes.rb
Tictactoe::Application.routes.draw do

  put 'games/move' => 'games#move', as: 'move'
  resources :games

  root :to => 'games#index', as: 'root'

end

app/models/game.rb
class Game < ActiveRecord::Base
  include GameKeeper
  serialize :squares, Array
  serialize :moves, Array
  attr_accessible :squares, :moves, :player_turn

  def move(square, mover)
    if mover == :player
      self.squares[square] = 'O'
    elsif mover == :ai
      self.squares[square] = 'X'
    end
    self.save
  end

end

app/models/global_constants.rb
module GlobalConstants
  WON = "You Won!".freeze
  LOST = "You Lost!".freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def create
    game = Game.new(squares: Array.new(9))
    game.move(4, :ai)
    game.save
    redirect_to game_path(game)
  end

  def show
    @game = Game.find_by_id(params[:id])
    @winner = GameKeeper::winner(@game)
    gon.winner = ""

  end

  def move
    @game = Game.find_by_id(params[:game])
    @player_square, @ai_square = make_moves(@game, params[:square].to_i)
    @winner = GameKeeper.winner(@game)
    gon.winner = @winner

    respond_to :js
  end

  private

  def make_moves(game,player_square)
    game.move(player_square, :player)
    ai_square = GameKeeper.ai_move(@game)
    game.move(ai_square, :ai) unless game.squares.compact.count == 9

    return player_square, ai_square
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  
end

app/views/games/_filled_square.html.erb
<td class="square_<%= index %>"><%= square %></td>

app/views/games/_game_board.html.erb
<div class="row">
  <div class="span6 offset3">
    <table class="table">
      <% @game.squares.each_with_index do |square, index| %>
        <% if (index + 1) % 3 == 1 %>
          <% if square.nil? %>
            <tr><%= render "nil_square", index: index  %>
          <% else %>
            <tr><%= render "filled_square", square: square, index: index %>
          <% end %>
        <% elsif (index + 1) % 3 == 0 %>
          <% if square.nil? %>
		  <%= render "nil_square", index: index  %></tr>
          <% else %>
            <%= render "filled_square", square: square, index: index %></tr>
          <% end %>
        <% else %>
          <% if square.nil? %>
		  <%= render "nil_square", index: index  %>
          <% else %>
            <%= render "filled_square", square: square, index: index %></td>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/games/_nil_square.html.erb
<td class="square_<%= index%>"><%= link_to "_", move_path(square: (index), game: params[:id]), {id: "square_#{(index)}", method: "put", class: "center-link", remote: "true"} %></td>

app/views/games/index.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1 class="text-center">Tic Tac Toeeee!</h1>
    <h2 class="text-center" id="new-game"><%= link_to 'New Game', games_path, method: 'post' %></h2>
  </div>
</div>

app/views/games/move.js.erb
/**
 * Created with JetBrains RubyMine.
 * User: matthewrieger
 * Date: 5/20/13
 * Time: 9:24 PM
 * To change this template use File | Settings | File Templates.
 */

    var ai_square = $("#square_<%= @ai_square %>");
    ai_square.after("X");
    ai_square.remove();

    var player_square = $("#square_<%= @player_square %>");
    player_square.after("O");
    player_square.remove();

    <% if @winner || @game.squares.compact.count == 9 %>
         $('#winner').find("h2").text("<%= @winner ||  raw("It's a Draw!") %>");
         $('#winner').slideDown("slow");
    <% end %>

app/views/games/show.html.erb
<div class="page-header">
  <div class="row">
    <div class="span6 offset3">
    <h1 class="text-center">Tic Tac Toeeeeee!</h1>
    </div>
  </div>

  <div class="row" id="winner">
    <div class="span6 offset3">
      <h2 class="text-error text-center"><%= @winner || "It's a draw!" %></h2> <br>
      <p class="text-center"><%= link_to "Play Again?", games_path, method: "post", class:"text-success"%></p>
    </div>
  </div>

<%= render 'game_board' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tictactoe</title>
  <%= include_gon init: true %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>

<footer><p>Created by Matthew Rieger</p> <p><a href="http://www.github.com/stctbone/tictactoe">Source Code</a><p></footer>
</body>
</html>